language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y sqlite3 python-apsw
install: 
    - "pip install -r requirements.txt"
script: py.test caterpillar
